export { default as Admin } from "./admin/Admin";
export { default as Back } from "./back/Back";
export { default as Bills } from "./bills/Bills";
export { default as Chargers } from "./chargers/Chargers";
export { default as Login } from "./login/Login";
export { default as MakeOrder } from "./make-order/MakeOrder";
export { default as OrderInfo } from "./order-info/OrderInfo";
export { default as Table } from "./table/Table";
export { default as User } from "./user/User";
